webblog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from webblogs import views

urlpatterns = [
    url(r'^', include('webblogs.urls', namespace="webblogs")),
    url(r'^admin/', admin.site.urls),
]

webblogs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<page>[0-9]+)/page$', views.index_page, name='index_page'),
    url(r'^(?P<post_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^new_post/$', views.new_post, name="new_post"),
    url(r'^(?P<post_id>[0-9]+)/edit/$', views.edit, name="edit"),
    url(r'^(?P<post_id>[0-9]+)/delete/$', views.delete, name="delete"),
]

webblogs/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    author = models.CharField(max_length=100)
    create_date = models.DateTimeField(auto_now_add=True)
    change_date = models.DateTimeField(auto_now=True)
    text = models.TextField(max_length=2000)
    def __unicode__(self):
        return u'%s: %s' % (self.author, self.text)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.ForeignKey('self', null=True, blank=True, related_name="comments", on_delete=models.CASCADE)
    author = models.CharField(max_length=100)
    create_date = models.DateTimeField(auto_now_add=True)
    email = models.CharField(max_length=50)
    text = models.TextField(max_length=500)
    def __unicode__(self):
        return u'%s: %s' % (self.author, self.text)

# Create your models here.

webblogs/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import *
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, InvalidPage

page_el = 5

def index(request):
    return index_page(request, 1)

def index_page(request, page):
    p = Post.objects.order_by('create_date')
    posts = Paginator(p, page_el)
    return render(request, 'webblogs/index.html', {'page': posts.page(page), 'range': posts.page_range})


def detail(request, post_id):
    if request.method == 'POST':
        com = None if request.POST['id'] == 'None' else Comment.objects.get(pk=request.POST['id'])
        Comment(post=Post.objects.get(pk=post_id),comment=com, author=request.POST['author'], email=request.POST['email'], text=request.POST['text']).save()
        return HttpResponseRedirect('/'+post_id)
    post = Post.objects.get(id = post_id)
    return render(request, 'webblogs/detail.html', {'post': post})

def new_post(request):
    if request.method == 'POST':
        post = Post(author=request.POST['author'], text=request.POST['text'])
        post.save()
        return HttpResponseRedirect('/'+str(post.pk))
    return render(request, 'webblogs/new_post.html')

def edit(request, post_id):
    post = Post.objects.get(pk=post_id)
    if request.method == 'POST':
        post.author = request.POST['author']
        post.text = request.POST['text']
        post.save()
        return HttpResponseRedirect('/' + post_id)
    return render(request, 'webblogs/edit.html', {'post': post})

def delete(request, post_id):
    if request.method == 'POST':
        Post.objects.get(pk = post_id).delete()
    return HttpResponseRedirect('/')

# Create your views here.

webblogs/templates/webblogs/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
 <head>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <script src="{% static "jquery.js"%}"></script>
    <script src="{% static "js/bootstrap.min.js"%}"></script>

     <style>
    body {
      padding-top: 70px;
      padding-bottom: 20px;
    }
  </style>
     <script>
    $(function()
    {
        $("button.btn-xs").click(function ()
        {
            $(this).parent().siblings("div.comments").slideToggle();
            return false;
        })
    });

    $(function()
    {
        $("a.form").click(function ()
        {
            $(this).siblings("div.form-comment").slideToggle("slow");
            return false;
        })
        $("a.form").siblings("div.form-comment").hide();
    });
</script>
 </head>
 <body>
 <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'webblogs:index' %}">WebBlog</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="{% block main %}{% endblock %}"><a href="{% url 'webblogs:index' %}">Главная</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
          {% block content %}{% endblock %}
    </div>

 </body>
</html>

webblogs/templates/webblogs/comment.html
<blockquote>
<footer>
    <button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-resize-vertical"></span></button>
    <span class="glyphicon glyphicon-user"></span> {{ comment.author }} |
    <span class="glyphicon glyphicon-calendar"></span> {{ comment.create_date|date }} |
    <span class="glyphicon glyphicon-time"></span> {{ comment.create_date|time }} |
    <span class="glyphicon glyphicon-envelope"></span> {{ comment.email }}
</footer>
<div class="comments">
    <p>{{ comment.text }}</p>
    <a class="form">Комменитровать</a>
    <div class="form-comment">
        <form action="{% url 'webblogs:detail' post.id%}" method="post" class="form-group">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ comment.id }}"/>
            <div class="form-group">
                <input type="text" class="form-control" name="author" id="author{{ comment.id }}" placeholder="Пользователь" required/>
            </div>
            <div class="form-group">
                <input type="email" class="form-control" name="email" id="email{{ comment.id }}" placeholder="Email" required/>
            </div>
            <div class="form-group">
                <textarea class="form-control" name="text" id="text{{ comment.id }}" placeholder="Текст сообщения" rows="3" required></textarea>
            </div>
            <button type="submit" class="btn btn-default">Отправить</button>
        </form>
    </div>
    {% for comment in comment.comments.all %}
        {% include "webblogs/comment.html" %}
    {% endfor %}
</div>
</blockquote>

webblogs/templates/webblogs/detail.html
{% extends "webblogs/base.html" %}
{% block content %}

        <h4>
            <small>
                <span class="glyphicon glyphicon-user"></span> {{ post.author }} |
                <span class="glyphicon glyphicon-calendar"></span> {{ post.create_date|date }}
                {% if post.create_date == post.change_date %}
                    (Изменен: {{ post.change_date|date }})
                {% endif %}
            </small>
        </h4>
        <p class="lead">{{ post.text }}</p>
        <form action = "{% url 'webblogs:delete' post.id%}" method = "post">
            {%  csrf_token %}
            <a role="button" class="btn btn-default" href="{% url 'webblogs:edit' post.id %}"><span class="glyphicon glyphicon-pencil"></span> Редактировать пост</a>
            <button class="btn btn-default"><span class="glyphicon glyphicon-remove"></span> Удалить пост</button>
        </form>
        <h2><small>Комментарии ({{ post.comment_set.count }})</small></h2>
        <div class="form-group">
        <a class="form">Комменитровать</a>
        <div class="form-comment">
            <form action="{% url 'webblogs:detail' post.id%}" method="post" class="form-group">
                {% csrf_token %}
                <input type="hidden" name="id" value="None"/>
                <div class="form-group">
                    <input type="text" class="form-control" name="author" id="author" placeholder="Пользователь" required/>
                </div>
                <div class="form-group">
                    <input type="email" class="form-control" name="email" id="email" placeholder="Email" required/>
                </div>
                <div class="form-group">
                    <textarea class="form-control" name="text" id="text" placeholder="Текст сообщения" rows="3" required></textarea>
                </div>
                <button type="submit" class="btn btn-default">Отправить</button>
            </form>
        </div>
        </div>
        {% for comment in post.comment_set.all%}
            {% if comment.comment == None %}
                {% include "webblogs/comment.html" %}
            {% endif %}
        {% endfor %}
{% endblock %}

webblogs/templates/webblogs/edit.html
{% extends "webblogs/base.html" %}
{% block content %}
    <center><h3>Редактировать пост</h3></center>
    <form class="form-horizontal" role="form" action="{% url 'webblogs:edit' post.id%}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="author" class="col-sm-2 control-label">Пользователь</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="author" id="author" placeholder="Имя пользоателя" value="{{ post.author }}" required>
            </div>
        </div>
        <div class="form-group">
            <label for="еуче" class="col-sm-2 control-label">Текст</label>
            <div class="col-sm-10">
                <textarea class="form-control" name="text" id="text" placeholder="Текст сообщения" rows="10" required>{{ post.text }}</textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Сохранить</button>
            </div>
        </div>
    </form>
{% endblock %}

webblogs/templates/webblogs/index.html
{% extends "webblogs/base.html" %}
{% block main %}active{% endblock %}
{% block content %}
    <div class="form-group">
     <a role="button" class="btn btn-default" href="{% url 'webblogs:new_post' %}"><span class="glyphicon glyphicon-plus"></span> Создать пост</a>
    </div>
    {% for post in page %}
        <blockquote>
            <p class="lead">{{ post.text }}</p>
                <div class="form-group">
                    <a role="button" href="{% url 'webblogs:detail' post.id%}" class="btn btn-default">Читать полностью</a>
                </div>
            <footer>
                <span class="glyphicon glyphicon-user"></span> {{ post.author }} |
                <span class="glyphicon glyphicon-calendar"></span> {{ post.create_date|date }}
                {% if post.create_date == post.change_date %}
                    (Изменен: {{ post.change_date|date }})
                {% endif %} |
                <span class="glyphicon glyphicon-comment"></span> {{ post.comment_set.count}}
            </footer>
        </blockquote>
    {% endfor %}
    <center>
        <ul class="pagination">
            {% if page.has_previous %}<li><a href="{% url 'webblogs:index_page' page.previous_page_number%}">&laquo;</a></li>{% endif %}
            {% for p in range%}
                    <li class="{% if p == page.number%} active {% endif %}"><a href="{% url 'webblogs:index_page' p%}">{{ p }}</a></li>
            {% endfor %}
            {% if page.has_next %}<li><a href="{% url 'webblogs:index_page' page.next_page_number%}">&raquo;</a></li>{% endif %}
        </ul>
    </center>
{% endblock %}

webblogs/templates/webblogs/new_post.html
{% extends "webblogs/base.html" %}
{% block content %}
    <center><h3>Создать новый пост</h3></center>

    <form class="form-horizontal" role="form" action="{% url 'webblogs:new_post'%}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="author" class="col-sm-2 control-label">Пользователь</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="author" id="author" placeholder="Имя пользоателя" required>
            </div>
        </div>
        <div class="form-group">
            <label for="еуче" class="col-sm-2 control-label">Текст</label>
            <div class="col-sm-10">
                <textarea class="form-control" name="text" id="text" placeholder="Текст сообщения" rows="10" required></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Создать</button>
            </div>
        </div>
    </form>
{% endblock %}